In [50]:
'''
Program to convert Decimal number into 6 base number system
'''

def Cnvrt_decimaltootherbase(num):
    if type(num)!=int:
        print('Please input a valid number')
        return 0
    if type(num)==int:
        dummy_lst=list()
        while num>0:
            
            dummy_lst.append(num%6)
            num=num//6
        dummy_lst.reverse()
        res = int("".join(map(str, dummy_lst)))
    return res
        
'''
Program to convert 6 base number into decimal number system
'''            
def Cnvrt_otherbasetointeger(num):
    res=0
    if type(num)!=int:
        print('Please input a valid number')
        return 0
    if type(num)==int:
        dummy_lst=list()
        while num>0:
            dummy_lst.append(num%10)
            num=num//10
    res=0
    l=len(dummy_lst)
    res=res+dummy_lst[l-1]*6

    while(l>2):
        res=(res+dummy_lst[l-2])*6
        l-=1
    
    res=res+dummy_lst[0]
    return res

In [46]:
i=Cnvrt_decimaltootherbase(223948)
print(i)

4444444


In [49]:
x=1545

dummy_lst=list()


y=x
i=1
num=x%10    
#x=x%10  

while(y//10>0):
    i=i+1
    y=y//10

#print(i)

for k in range(1,i+1):
    dummy_lst.append(x%10)
    #print(x%10)
    #num = (num + x)*6
    x=x//10
    #print(x)
#dummy_lst.reverse()
res=0

print(dummy_lst)
l=len(dummy_lst)
res=res+dummy_lst[l-1]*6

while(l>2):
    #res=(res+dummy_lst[l-1])*6+dummy_lst[l-2]
    res=(res+dummy_lst[l-2])*6
    
    l-=1
    
res=res+dummy_lst[0]
print(res)
    

[5, 4, 5, 1]
425


In [52]:
Cnvrt_otherbasetointeger(4444444)

223948

In [3]:
l1=[1,2,3,4,5]
print(l1[3:])

[4, 5]


In [65]:
#str='abcd'
#print(l1)
def fun_Per(l1):
    if len(l1)==1:
        return l1
    if len(l1)==0:
        return []

    for i in range(len(l1)):
        strt=l1[i]
        
        raw_str= l1[:i] + l1[i+1:]
        #print(raw_str)
    
        #print(raw_str)
        for j in fun_Per(raw_str):
            dummy_lst.append([strt]+j)
            print(dummy_lst)
    return dummy_lst    
        
        

In [66]:
fun_Per('abcd')

TypeError: can only concatenate list (not "str") to list

In [34]:
l1=list()
l1='abcd'
print(l1)

abcd


In [57]:
#Distance between two points in 3 dimesion
import math
(x1,y1,z1)=(10,20,30)
(x2,y2,z2)=(15,15,15)
math.sqrt((x2-x1)**2+(y2-y1)**2+(z2-z1)**2)
    


16.583123951777

In [1]:
0b10+0b11

5

In [2]:
bin(100)

'0b1100100'

In [1]:
~4

-5

In [2]:
~0b100101

-38

In [22]:

x=12
y=17
print(bin(x))
print(bin(y))
x^y

0b1100
0b10001


29

In [27]:
#Use XOR to swap without using third variable
x=70
y=800
x=x^y
y=x & (x^y)
x=x^y
print(x,y)

800 70


In [19]:
#Tower of Hanoi


def Tower_of_Hanoi_1(n,Source,target,Aux):
    print(f"Move {n} from {Source} to {target}")

    
def Tower_of_Hanoi_2(n,Source,target,Aux):
    #print(f"Move 1 from {Source} to {Aux}")
    #print(f"Move 2 from {Source} to {target}")
    #print(f"Move 3 from {Aux} to {target}")
    Tower_of_Hanoi_1(n,Source,Aux,target)
    Tower_of_Hanoi_1(n-1,Source,target,Aux)
    Tower_of_Hanoi_1(n,Aux,target,Source)
    
def Tower_of_Hanoi(n,Source,target,Aux):
    if n==1:
        Tower_of_Hanoi_1(n,Source,target,Aux)
    else:
        Tower_of_Hanoi(n-1,Source,Aux,target)
        Tower_of_Hanoi_1(n,Source,target,Aux)
        Tower_of_Hanoi(n-1,Aux,target,Source)
        
    

In [14]:
Tower_of_Hanoi_1(0,'A','C','B')

Move 0 from A to C


In [20]:
Tower_of_Hanoi(3,'A','C','B')

Move 1 from A to C
Move 2 from A to B
Move 1 from C to B
Move 3 from A to C
Move 1 from B to A
Move 2 from B to C
Move 1 from A to C


In [36]:
#Multiply without *
def multy_recursion(a,b):
    if a==0 or b==0:
        return 0
    else:
        return multy_recursion(a,b-1)+a
    
    


In [37]:
multy_recursion(3,4)

12

In [1]:
#HCF with recursion
def HCF_Recursion(a,b):
    if a > b:
        a, b = b, a
    if a == 0:
        return 0
    remainder = b % a
    if remainder == 0:
        return a
    return HCF_Recursion(remainder, a)
        

In [2]:
HCF_Recursion(15,30)

15

In [3]:
def is_online(x1,x2,x):
    if(x>=x1 and x<=x2):
        return True
    if(x>=x2 and x<=x1):
        return False
    return False
    

In [4]:
is_online(1,4,3)

True

In [5]:
is_online(-3,-2,-1)

False

In [18]:
def is_inside_rectangle(x1,y1,x2,y2,x,y):
    if((x>=x1 and x<=x2) and (y>=y1 and y<=y2) or (x<=x1 and x>=x2) and (y<=y1 and y>=y2)):
        return True
    else:
        return False

In [15]:
is_inside_rectangle(1,2,3,4,2,3)

True

In [19]:
is_inside_rectangle(3,4,1,2,2,3)

True

In [20]:
is_inside_rectangle(-1,-2,3,4,2,3)

True

In [21]:
is_inside_rectangle(-1,2,-3,-4,-5,-6)

False

In [22]:
print(is_inside_rectangle(1, 2, 3, 4, 2, 3) == True)
print(is_inside_rectangle(-1, -2, -3, -4, -2, -3) == True)
print(is_inside_rectangle(3, 4, 1, 2, 2, 3) == True)
print(is_inside_rectangle(-3, -4, -1, -2, -2, -3) == True)
print(is_inside_rectangle(1, 2, 3, 4, 5, 6) == False)
print(is_inside_rectangle(-1, -2, -3, -4, -5, -6) == False)
print(is_inside_rectangle(3, 4, 1, 2, 5, 6) == False)
print(is_inside_rectangle(-3, -4, -1, -2, -5, -6) == False)

print(is_inside_rectangle(-1, -2, 3, 4, 2, 3) == True)
print(is_inside_rectangle(1, 2, -3, -4, -2, -3) == True)
print(is_inside_rectangle(3, 4, -1, -2, 2, 3) == True)
print(is_inside_rectangle(-3, -4, 1, 2, -2, -3) == True)

True
True
True
True
True
True
True
True
True
True
True
True


In [27]:
def test_call_rectangle(a):
    print(a(1, 2, 3, 4, 2, 3) == True)
    print(is_inside_rectangle(-1, -2, -3, -4, -2, -3) == True)
    print(is_inside_rectangle(3, 4, 1, 2, 2, 3) == True)
    print(is_inside_rectangle(-3, -4, -1, -2, -2, -3) == True)
    print(is_inside_rectangle(1, 2, 3, 4, 5, 6) == False)
    print(is_inside_rectangle(-1, -2, -3, -4, -5, -6) == False)
    print(is_inside_rectangle(3, 4, 1, 2, 5, 6) == False)
    print(is_inside_rectangle(-3, -4, -1, -2, -5, -6) == False)

    print(is_inside_rectangle(-1, -2, 3, 4, 2, 3) == True)
    print(is_inside_rectangle(1, 2, -3, -4, -2, -3) == True)
    print(is_inside_rectangle(3, 4, -1, -2, 2, 3) == True)
    print(is_inside_rectangle(-3, -4, 1, 2, -2, -3) == True)


In [26]:
test_call_rectangle(is_inside_rectangle)

True
True
True
True
True
True
True
True
True
True
True
True


In [ ]:
#in a line what will be the value of y if x is know.

In [34]:
#Tower of Hanoi-- Tripti


def Tower_of_Hanoi_oth(n,Source,target,Aux):
        print(f"Move {n} from {Source} to {target}")

#def Tower_of_Hanoi_odd(n,Source,target,Aux):
#    print(f"Move {n} from {Source} to {target}")
 #   #print(f"Move {n} from {Source} to {Aux}")

def Tower_of_Hanoi_trpt(n,Source,target,Aux):
    if n<=0:
        return 1
    elif n==1:
        print(f"Move {n} from {Source} to {target}")
        
        
   
    else:
        Tower_of_Hanoi_trpt(n-1,Source,Aux,target)
        Tower_of_Hanoi_oth(n,Source,target,Aux)
        Tower_of_Hanoi_trpt(n-1,Aux,target,Source)
        
        
        
    
    
    
         
        



In [37]:
Tower_of_Hanoi_trpt(5,'A','C','B')

Move 1 from A to C
Move 2 from A to B
Move 1 from C to B
Move 3 from A to C
Move 1 from B to A
Move 2 from B to C
Move 1 from A to C
Move 4 from A to B
Move 1 from C to B
Move 2 from C to A
Move 1 from B to A
Move 3 from C to B
Move 1 from A to C
Move 2 from A to B
Move 1 from C to B
Move 5 from A to C
Move 1 from B to A
Move 2 from B to C
Move 1 from A to C
Move 3 from B to A
Move 1 from C to B
Move 2 from C to A
Move 1 from B to A
Move 4 from B to C
Move 1 from A to C
Move 2 from A to B
Move 1 from C to B
Move 3 from A to C
Move 1 from B to A
Move 2 from B to C
Move 1 from A to C


In [13]:
def power(n,x):
    if x==0:
        return 1
    y= n*power(n,x-1)
    return y
    

In [14]:
power(2,3)

8

In [ ]:
'''Problem 1:
articles = ['a', 'the', 'that', 'this']

adjectives = ["good", "bad", "nice", "blue", "light"]

words = ["city", "sky", "water", "person"]

print all possible combinations: a good city a good sky ... the bad water ...''''

# Problem 2: Find average of list of numbers
#Problem 3: Statdard Deviation

In [2]:
#Problem 1:print all possible combinations
articles = ['a', 'the', 'that', 'this']

adjectives = ["good", "bad", "nice", "blue", "light"]

words = ["city", "sky", "water", "person"]

for i in articles:
    for j in adjectives:
        for k in words:
            print(i+" "+ j+ " "+k)

a good city
a good sky
a good water
a good person
a bad city
a bad sky
a bad water
a bad person
a nice city
a nice sky
a nice water
a nice person
a blue city
a blue sky
a blue water
a blue person
a light city
a light sky
a light water
a light person
the good city
the good sky
the good water
the good person
the bad city
the bad sky
the bad water
the bad person
the nice city
the nice sky
the nice water
the nice person
the blue city
the blue sky
the blue water
the blue person
the light city
the light sky
the light water
the light person
that good city
that good sky
that good water
that good person
that bad city
that bad sky
that bad water
that bad person
that nice city
that nice sky
that nice water
that nice person
that blue city
that blue sky
that blue water
that blue person
that light city
that light sky
that light water
that light person
this good city
this good sky
this good water
this good person
this bad city
this bad sky
this bad water
this bad person
this nice city
this nice sky
t

In [8]:

x=[1,2,3,4,5,6,7,8,9,10]
sum=0
count=0
average=0
for i in x:
    sum=sum+i
    count+=1
average= sum/count  
print(average)

    
    

5.5


In [3]:
#Problem 3: Statdard Deviation

import math
x=[1,2,3,4,5,6,7,8,9,10]
diff_x=list()
sumx=0
count=0
for i in x:
    sumx=sumx+i
    count+=1
average= sumx/count 

for i in range(len(x)):
   # print(i)
    p=average-x[i]
    #print(p)
    diff_x.append(p**2)
    #print(p)    

print(math.sqrt(sum(diff_x)/count))    

    #diff_x=diff_x**2
#print(x,average,diff_x)    

2.8722813232690143


In [ ]:

#'''Sandeep'''
# a + b + c = 10 -> [1, 1, 1, 10]
# 2a + 3b + 4c = 50 [2, 3, 4, 50]
# 3a + 5b - 8c = 100 [3, 5, -8, 100]

def solve(eqns):
    if len(eqns) != len(eqns[0]) - 1:
        return None
    if len(eqns) == 1:
        #[0 10]
        eqn = eqns[0]
        return [eqn[1]/eqn[0]] # check if eqn[0] is 0
    # eliminiate one variable and call solve(new_eqns)
    new_equans = eliminate_n(eqns)
    soln_1 = solve(new_equans)
    
    # put the soln in first equation i.e. eqn[0]
    return [result, result1]

eq1 = [1, 1, 1, 10]
eq2 = [2, 3, 4, 50]
eq3 = [3, 5, -8, 100]
eqns = [eq1, eq2, eq3]
result = solve(eqns)

In [51]:
#eq2-eq1
def find_multiplier(Marr,Mlen):
    
    mul=[]
    for i in range(1,Mlen):
        if Marr[0][0]>Marr[i][0]:
            mul.append(Marr[0][0]/Marr[i][0])
        else:
            mul.append(Marr[i][0]/Marr[0][0])
    
    return mul    

def eliminate_n(arr):
    L= len(arr)
    k=0
    result = []
    
    #for i in range(0,L-2):
   
    #print(result)
    new_eqns =[]
    for i in range(1,L):
        res=[]
        result=find_multiplier(arr,L)
        
        for j in range(1,L+1):
            x=arr[i][j]-arr[0][j]*result[k]
            
            res.append(x)
        new_eqns.append(res)
            
        k+=1 
    
      
    
    return new_eqns
        
            
def solv(eqns):
    print("SOLVE",eqns)
    if len(eqns) != (len(eqns[0]) - 1):
        return None
    l=len(eqns)
    if len(eqns) == 1:
        eqn = eqns[0]
        if  eqn[0]==0:
            return("Can't solve this equation" )
        else:
            return eqn[1]/eqn[0]
    new_equans = eliminate_n(eqns)
    print(new_equans)
    soln_1 = solv(new_equans)
    
    
    
    

In [52]:
eq1 = [1, 1, 1, 10]
eq2 = [2, 3, 4, 50]

eq3 = [3, 5, -8, 100]
eqns = [eq1, eq2, eq3]
#find_multiplier(eq1,eq2)
eliminate_n(eqns)
#mul1 = find_multiplier(eq1,eq2)
#mul2=find_multiplier(eq1,eq3)
#print(mul1,mul2)
#solv(eqns)


[[1.0, 2.0, 30.0], [2.0, -11.0, 70.0]]

In [5]:

arr = [[2,3, 1],[4,5,6]]
# [A] 2a + 3b = 1
# [B] 4a + 5b = 6
# [B] - A*2




In [26]:
find_multiplier(eq1,eq2)

2.0

In [43]:
import math
math.sqrt(424)

20.591260281974

In [78]:
find_multiplier([[1.0, 2.0, 30.0], [2.0, -11.0, 70.0]],2)

[2.0]

In [15]:
# Problem1:
# 2y = 40 -> [2, 40]
# y = 40/2 -> [20]

def solve1(arr):
    
    tmp=arr[1]/arr[0]
    return (tmp)

# Input: [3, 15]
# Expected: [5]

In [25]:
y=solve1([6,12])
solve_substitute([2,5,78],y)


[34.0, 2.0]

In [45]:
# Problem 2

#2x + 5y = 78, y=2
#x = (78 - 5*2)/2

def solve_substitute(eqn, prev_ans):
    lst=[]
    L=len(prev_ans)
    eqlen=len(eqn)
    x=0
    
    for i in range(L):
        x=x+prev_ans[i]*eqn[i+1]
        #print('Multy value',x)
    
    x=(eqn[eqlen-1]-x)/eqn[0]
    
    lst.append(x)
    lst.append(prev_ans)
    return lst

#Example 1:
#solve_substitute([2, 5, 78], [2])
#expected_answer: [34, 2]

#Example 2:
# 3x + 5y - 10z = 30
# y, z = [1, 2]
# 3*x + 5*1 - 10*2 = 30
# x = (30 - (5*1 - 10*2))/3

#solve_substitute([3, 5, -10, 30], [1, 2]), 
#Expected_answer: [15, 1, 2]

In [46]:
solve_substitute([3, 5, -10, 30], [1, 2])

[15.0, [1, 2]]

In [47]:
solve_substitute([2, 5, 78], [2])

[34.0, [2]]

In [60]:
# Problem 3
##A. 2x + 3y = 10
##B. 4x - 5y = 50


##Multiplier = 4/2
##C. B - 2*A
##C. -11y = 30
def find_multiplier(Marr,Mlen):
    
    mul=[]
    for i in range(1,Mlen):
        if Marr[0][0]>Marr[i][0]:
            mul.append(Marr[0][0]/Marr[i][0])
        else:
            mul.append(Marr[i][0]/Marr[0][0])
    
    return mul   

def reduce(arr):
    L= len(arr)
    k=0
    result = []
    
    #for i in range(0,L-2):
   
    #print(result)
    new_eqns =[]
    for i in range(1,L):
        res=[]
        result=find_multiplier(arr,L)
        
        for j in range(1,L+1):
            x=arr[i][j]-arr[0][j]*result[k]
            
            res.append(x)
        new_eqns.append(res)
            
        k+=1 
       
    return new_eqns

#input = [[2, 3, 10],
#    [4, -5, 50]]
#'''result = reduce(input)
#result = [-11, 30]

#result = reduce([
#    [1, 2, 3, 4], #x + 2y + 3z = 4
#   [2, 2, 4, 10],
#    [3, 4, 2, 30],
#])
#result: [
#    [ -2, -2, 2], #eqn2 - 2*eqn1
#    [-2, -7, 18],  #eqn3 - 2*eqn1
#]'''


In [63]:
reduce([[1, 2, 3, 4],[2, 2, 4, 10],[3, 4, 2, 30]])

[[-2.0, -2.0, 2.0], [-2.0, -7.0, 18.0]]

In [64]:
reduce([[2, 3, 10],[4, -5, 50]])

[[-11.0, 30.0]]

In [84]:
# Code convert to number a decimal numbers
# Problem 4: 
num = "१३७.७"
def convert(num):
    dic_numbers={'०':0,'१':1,'२':2,'३':3,'४':4,'५':5,'६':6,'७':7,'८':8,'९':9,'.':'.'}
    # print(137.7)
    for i in range(len(num)):
        for j,k in dic_numbers.items():
                   if num[i]==j:
                       print(k,end="")
                   
                   
                   
        

In [86]:
convert("१३७.७")

137.7

In [69]:
ord('1')

49

In [87]:
convert("२३४.८")

234.8

In [1]:
for i in range(200):
    print(2406+i, chr(2406+i))
    
for i in range(49):
    print(49+i, chr(49+i))    
    

2406 ०
2407 १
2408 २
2409 ३
2410 ४
2411 ५
2412 ६
2413 ७
2414 ८
2415 ९
2416 ॰
2417 ॱ
2418 ॲ
2419 ॳ
2420 ॴ
2421 ॵ
2422 ॶ
2423 ॷ
2424 ॸ
2425 ॹ
2426 ॺ
2427 ॻ
2428 ॼ
2429 ॽ
2430 ॾ
2431 ॿ
2432 ঀ
2433 ঁ
2434 ং
2435 ঃ
2436 ঄
2437 অ
2438 আ
2439 ই
2440 ঈ
2441 উ
2442 ঊ
2443 ঋ
2444 ঌ
2445 ঍
2446 ঎
2447 এ
2448 ঐ
2449 ঑
2450 ঒
2451 ও
2452 ঔ
2453 ক
2454 খ
2455 গ
2456 ঘ
2457 ঙ
2458 চ
2459 ছ
2460 জ
2461 ঝ
2462 ঞ
2463 ট
2464 ঠ
2465 ড
2466 ঢ
2467 ণ
2468 ত
2469 থ
2470 দ
2471 ধ
2472 ন
2473 ঩
2474 প
2475 ফ
2476 ব
2477 ভ
2478 ম
2479 য
2480 র
2481 ঱
2482 ল
2483 ঳
2484 ঴
2485 ঵
2486 শ
2487 ষ
2488 স
2489 হ
2490 ঺
2491 ঻
2492 ়
2493 ঽ
2494 া
2495 ি
2496 ী
2497 ু
2498 ূ
2499 ৃ
2500 ৄ
2501 ৅
2502 ৆
2503 ে
2504 ৈ
2505 ৉
2506 ৊
2507 ো
2508 ৌ
2509 ্
2510 ৎ
2511 ৏
2512 ৐
2513 ৑
2514 ৒
2515 ৓
2516 ৔
2517 ৕
2518 ৖
2519 ৗ
2520 ৘
2521 ৙
2522 ৚
2523 ৛
2524 ড়
2525 ঢ়
2526 ৞
2527 য়
2528 ৠ
2529 ৡ
2530 ৢ
2531 ৣ
2532 ৤
2533 ৥
2534 ০
2535 ১
2536 ২
2537 ৩
2538 ৪
2539 ৫
2540 ৬
2541 ৭
2542 ৮
2543 ৯
2544 ৰ
2545 ৱ
2546 ৲
2547 ৳
2548 ৴

## Write your own add digit arrays
[1,1,2] + [1,2,1] -> [2, 3,3]
[1,2] + [1,0] -> [2,2]


# Write the matrix multiplication

In [59]:
##  Write the matrix multiplication
import numpy as np

def matrix_multiplication(Mtrx1,Mtrx2):
       
    Mtrx1_row=len(Mtrx1)
    Mtrx1_col=len(Mtrx1[0])
    
    
    Mtrx2_row=len(Mtrx2)
    Mtrx2_col=len(Mtrx2[0])
    
    print(f'first Mtrix No of Rows = {Mtrx1_row},first Matrix No of column = {Mtrx1_col},Second Mtrix Rows = {Mtrx2_row},Second Mtrix Cols = {Mtrx2_col}')
    
    Mtrx3=np.zeros((Mtrx1_row,Mtrx1_col),dtype=np.int16)
    #print(Mtrx3)
    
    if Mtrx1_col==Mtrx2_row:
        for i in range(Mtrx1_row):
            for j in range (Mtrx1_col):
                #Mtrx3[i][j]=0
                for k in range (Mtrx1_col):
                    Mtrx3[i][j]=Mtrx3[i][j]+Mtrx1[i][k]*Mtrx2[k][j]
                #print(Mtrx3[i][j]) for QC purpose   

        print(Mtrx3)
    else:
        print('Error: Number of col in first matrix should be equal to number of rows of second matrix')
              
    
    

In [62]:
Mtrx1=[[1,2,1],[3,1,7],[2,3,9]]
Mtrx2=[[2,1,3],[1,2,2],[1,1,2]]
len(Mtrx2)

3

In [61]:
Mtrx1=[[1,2,1],[3,1,7],[2,3,9]]
Mtrx2=[[2,1,3],[1,2,2],[1,1,2]]

matrix_multiplication(Mtrx1,Mtrx2)

first Mtrix No of Rows = 3,first Matrix No of column = 3,Second Mtrix Rows = 3,Second Mtrix Cols = 3
[[ 5  6  9]
 [14 12 25]
 [16 17 30]]


In [52]:
Mtrx1=[[2,3,1],[3,3,1],[4,5,4]]
Mtrx2=[[1,14,23],[8,9,0],[0,8,3]]

matrix_multiplication(Mtrx1,Mtrx2)

first Mtrix No of Rows = 3,first Matrix No of column = 3,Second Mtrix Rows = 3,Second Mtrix Cols = 3
[[ 26  63  49]
 [ 27  77  72]
 [ 44 133 104]]


In [63]:
Mtrx1=[[1,2,3],[4,2,1]]
Mtrx2=[[1,2,3],[6,5,4],[6,4,2]]

matrix_multiplication(Mtrx1,Mtrx2)

first Mtrix No of Rows = 2,first Matrix No of column = 3,Second Mtrix Rows = 3,Second Mtrix Cols = 3
[[31 24 17]
 [22 22 22]]


In [64]:
Mtrx1=[[1,2,3],[6,5,4],[6,4,2]]
Mtrx2=[[1,2,3],[4,2,1]]


matrix_multiplication(Mtrx1,Mtrx2)

first Mtrix No of Rows = 3,first Matrix No of column = 3,Second Mtrix Rows = 2,Second Mtrix Cols = 3
Error: Number of col in first matrix should be equal to number of rows of second matrix


In [42]:
def add_digit_decimals(num_str1, num_str2): #"2.3", "4.56" -> "6.86"
    result1=[]
    part2=[]
    result2=[]
    i=0
    while num_str1[i]!='.':
        i+=1
        
    part1=num_str1[:i]
    part2=num_str1[i+1:]
    #print(part1,part2)
    
    i=0
    while num_str2[i]!='.':
        i+=1
        
    part3=num_str2[:i]
    part4=num_str2[i+1:]
    #print(part1,part2,part3,part4)
    lst1=list(part2)
    lst2=list(part4)
    
   
    
    if len(lst2)>len(lst1):
        for i in range(len(lst1),len(lst2)):
            lst1.append('0')
    i = len(lst1) - 1
    j = len(lst2) - 1
    result = []
    carryover = 0
    r=0
    while i > -1 or j > -1:
        if i >= 0:
            n1 = int(lst1[i])
        else:
            n1 = 0
        
        if j >= 0:
            n2 = int(lst2[j])
        else:
            n2 = 0
        r = n1 + n2 + carryover
#         print(f"{n1} + {n2} -> {r}")
        result.append(r%10)
        carryover = r // 10
        i -= 1
        j -= 1
    
    number= int(part1)+int(part3)
    if carryover > 0:
        number+=carryover
    result.reverse()
    dec=''
    for i in result:
        dec+=str(i)
    print(number,'.',dec)   
          

In [43]:
add_digit_decimals("2.3", "4.56")
add_digit_decimals("47.32", "4.56")
add_digit_decimals("47.32", "4.76")

6 . 86
51 . 88
52 . 08


In [73]:
# Write your own add digit arrays
#[1,1,2] + [1,2,1] -> [2, 3,3]
#[1,2] + [1,0] -> [2,2]

def add_digit(num_str1, num_str2):
    result=[]
    if len(num_str1)==len(num_str2):
        
        for i in range(len(num_str1)):
            result.append(num_str1[i]+num_str2[i])
        return (result)
    else:
        print("Error: length should be same for both array")



In [74]:
add_digit([1,1,2],[1,2,1])

[2, 3, 3]

In [79]:
add_digit([1,2],[1,0])

[2, 2]

In [75]:
add_digit([1,2,1],[1,0])

Error: length should be same for both array


In [115]:
2.56+2.3

4.859999999999999

In [116]:
56+3

59

In [117]:
2.3+2.56

4.859999999999999